language: elixir
matrix:
  include:
    - elixir: 1.3
      otp_release: 18.1
      services: docker
    - elixir: 1.4
      otp_release: 19.1
      services: docker
    - elixir: 1.5
      otp_release: 20.0
      services: docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - mix credo --strict
  - mix test
after_script:
  - mix inch.report
